/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountSettingsRouteImport } from './routes/account-settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoVideoUUIDRouteImport } from './routes/video/$videoUUID'
import { Route as VideoVideoUUIDShareRouteImport } from './routes/video/$videoUUID/share'
import { Route as VideoVideoUUIDEditRouteImport } from './routes/video/$videoUUID/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account-settings',
  path: '/account-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoVideoUUIDRoute = VideoVideoUUIDRouteImport.update({
  id: '/video/$videoUUID',
  path: '/video/$videoUUID',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoVideoUUIDShareRoute = VideoVideoUUIDShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => VideoVideoUUIDRoute,
} as any)
const VideoVideoUUIDEditRoute = VideoVideoUUIDEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => VideoVideoUUIDRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/login': typeof LoginRoute
  '/video/$videoUUID': typeof VideoVideoUUIDRouteWithChildren
  '/video/$videoUUID/edit': typeof VideoVideoUUIDEditRoute
  '/video/$videoUUID/share': typeof VideoVideoUUIDShareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/login': typeof LoginRoute
  '/video/$videoUUID': typeof VideoVideoUUIDRouteWithChildren
  '/video/$videoUUID/edit': typeof VideoVideoUUIDEditRoute
  '/video/$videoUUID/share': typeof VideoVideoUUIDShareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/login': typeof LoginRoute
  '/video/$videoUUID': typeof VideoVideoUUIDRouteWithChildren
  '/video/$videoUUID/edit': typeof VideoVideoUUIDEditRoute
  '/video/$videoUUID/share': typeof VideoVideoUUIDShareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-settings'
    | '/login'
    | '/video/$videoUUID'
    | '/video/$videoUUID/edit'
    | '/video/$videoUUID/share'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-settings'
    | '/login'
    | '/video/$videoUUID'
    | '/video/$videoUUID/edit'
    | '/video/$videoUUID/share'
  id:
    | '__root__'
    | '/'
    | '/account-settings'
    | '/login'
    | '/video/$videoUUID'
    | '/video/$videoUUID/edit'
    | '/video/$videoUUID/share'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  LoginRoute: typeof LoginRoute
  VideoVideoUUIDRoute: typeof VideoVideoUUIDRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-settings': {
      id: '/account-settings'
      path: '/account-settings'
      fullPath: '/account-settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$videoUUID': {
      id: '/video/$videoUUID'
      path: '/video/$videoUUID'
      fullPath: '/video/$videoUUID'
      preLoaderRoute: typeof VideoVideoUUIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$videoUUID/share': {
      id: '/video/$videoUUID/share'
      path: '/share'
      fullPath: '/video/$videoUUID/share'
      preLoaderRoute: typeof VideoVideoUUIDShareRouteImport
      parentRoute: typeof VideoVideoUUIDRoute
    }
    '/video/$videoUUID/edit': {
      id: '/video/$videoUUID/edit'
      path: '/edit'
      fullPath: '/video/$videoUUID/edit'
      preLoaderRoute: typeof VideoVideoUUIDEditRouteImport
      parentRoute: typeof VideoVideoUUIDRoute
    }
  }
}

interface VideoVideoUUIDRouteChildren {
  VideoVideoUUIDEditRoute: typeof VideoVideoUUIDEditRoute
  VideoVideoUUIDShareRoute: typeof VideoVideoUUIDShareRoute
}

const VideoVideoUUIDRouteChildren: VideoVideoUUIDRouteChildren = {
  VideoVideoUUIDEditRoute: VideoVideoUUIDEditRoute,
  VideoVideoUUIDShareRoute: VideoVideoUUIDShareRoute,
}

const VideoVideoUUIDRouteWithChildren = VideoVideoUUIDRoute._addFileChildren(
  VideoVideoUUIDRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  LoginRoute: LoginRoute,
  VideoVideoUUIDRoute: VideoVideoUUIDRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
